backend:
  name: git-gateway
  # repo: "ECNTechnology/knowledge-base"
  branch: Production # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/.vuepress/public/images"
public_folder: "/images"
collections:
  - name: "cloud-dial" # Used in routes, e.g., /admin/collections/blog
    label: "Cloud Dial articles" # Used in the UI
    folder: "/guides/cloud-dial" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Body", name: "body", widget: "markdown"}